version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend